apiVersion: v1
kind: Service
metadata:
  name: my-node-api-service
  labels:
    name: my-node-api
spec:
  type: LoadBalancer
  selector:
    app: my-node-api
  ports:
    - port: 8087
      targetPort: 8087